# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/59f5b271-11c1-41f9-927d-ed3221a6b404";
      fsType = "btrfs";
      options = [ "subvol=@" "compress=zstd:3" "noatime" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/59f5b271-11c1-41f9-927d-ed3221a6b404";
      fsType = "btrfs";
      options = [ "subvol=@nix" "compress=zstd:3" "noatime" ];
    };

  fileSystems."/var/log" =
    { device = "/dev/disk/by-uuid/59f5b271-11c1-41f9-927d-ed3221a6b404";
      fsType = "btrfs";
      options = [ "subvol=@log" "compress=zstd:3" "noatime" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/59f5b271-11c1-41f9-927d-ed3221a6b404";
      fsType = "btrfs";
      options = [ "subvol=@home" "compress=zstd:3" "noatime" ];
    };

  # Second disk: data-storage (SSD 447Go)
  fileSystems."/mnt/backup" =
    { device = "/dev/disk/by-uuid/c6cd6dd5-d4a5-4de4-b179-1fecd2cc9c3e";
      fsType = "btrfs";
      options = [ "subvol=@backup" "compress=zstd:3" "noatime" ];
    };

  fileSystems."/mnt/storage" =
    { device = "/dev/disk/by-uuid/c6cd6dd5-d4a5-4de4-b179-1fecd2cc9c3e";
      fsType = "btrfs";
      options = [ "subvol=@storage" "compress=zstd:3" "noatime" ];
    };

  fileSystems."/mnt/games" =
    { device = "/dev/disk/by-uuid/c6cd6dd5-d4a5-4de4-b179-1fecd2cc9c3e";
      fsType = "btrfs";
      options = [ "subvol=@games" "compress=zstd:3" "noatime" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/83F7-5789";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
